# Generated by Django 3.1 on 2023-01-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230103_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.CharField(default='author', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='judul',
            field=models.CharField(max_length=100),
        ),
    ]
